#!/usr/bin/env python3
"""What the conversion costs and buys in EMULATED time -- computed, not timed.

Wall time in this environment is not a usable readout (TODO.md's ~5.7 s host
stall; and the emulator-free warm-up control moved 7 s -> 14 s between the two
batteries here). The emulated timeline is DETERMINISTIC and is generated by
`omsx_repl._tcl` from the case's own lines, so it can be read off exactly with
no emulator at all.

  T_end   the last scheduled instant -- when the run exits WITHOUT
          capture-on-signal (capture at t_run+step, then cap_gap)
  t_run   the last injection -- when the watchpoint arms, i.e. the FLOOR on
          when a converted run can exit

`T_end(before) - t_run(after)` is therefore the BEST CASE reclaim per case, and
`T_end(after) - T_end(before)` is what the longer marked line costs in extra
KEYBUF chunk slots -- the part that is easy to forget.
"""
import re, sys, os
sys.path.insert(0, "probes/lib"); sys.path.insert(0, "probes/basic")
import omsx_repl


def sched(lines, *, boot, step, cap_gap, reset):
    slots = []
    tcl = omsx_repl._tcl("/dev/null", [("direct", list(reset) + lines)],
                         boot, step, cap_gap, (), "screen", None, 12.0, (),
                         slots, hb_path=None, settle_n=0,
                         sentinel=(0xE000, 255), run_gap=None,
                         sentinel_capture=True)
    times = [float(m) for m in re.findall(r"after time ([\d.]+)", tcl)]
    # the redundant safety exit is scheduled T_end+30; the real end is the one
    # before it, and t_run is the LAST `__inj`/`__key` slot.
    inj = [float(m) for m in
           re.findall(r"after time ([\d.]+) \{ __(?:inj|key) ", tcl)]
    return max(times) - 30.0, max(inj)


def report(name, before, after, **kw):
    eb, rb = sched(before, **kw)
    ea, ra = sched(after, **kw)
    print(f"  {name:<26} end {eb:6.1f} -> {ea:6.1f} scheduled "
          f"({ea-eb:+5.1f})   t_run {rb:6.1f} -> {ra:6.1f}   "
          f"best-case reclaim {eb-ra:+6.1f} emulated s")
    return eb - ra, ea - eb


import basic_probe_penderr as P, basic_probe_screenerr as S
import basic_probe_stmtpend as T, basic_probe_tmfp as M
import basic_probe_lineerr as L, basic_probe_deffn as D

print("PER CASE, in emulated seconds (RUN..exit).  '+' on the middle column is")
print("what the longer marked line COSTS in extra 38-char KEYBUF chunk slots.\n")

for mod, nm, stmt in ((P, "penderr", "WIDTH 40"), (S, "screenerr", "SCREEN 2"),
                      (T, "stmtpend", "WIDTH 40"), (M, "tmfp", "WIDTH 40")):
    for side in ("vg8020", "cf3300", "zb"):
        cfg = mod.SIDES[side]
        raw = ([ln.format(stmt=stmt) for ln in
                (mod.TEMPLATES["t"] if nm == "stmtpend" else mod.TRAP_PROG)])
        report(f"{nm}/{side}", raw + ["RUN"],
               mod.program("t", stmt) + ["RUN"],
               boot=cfg["boot"], step=cfg["step"], cap_gap=2.5,
               reset=cfg["reset"])
    print()

for side in ("vg8020", "cf3300", "zb"):
    cfg = L.SIDES[side]
    rd = L.GRPAC_RD
    raw = [ln.format(stmt="LINE(11,12)-(20,21)", seed=L.S2, **rd)
           for ln in L.TRAP_PROG]
    for lab, st in (("m.ok", cfg["step"]), ("c.32767", 12.0)):
        report(f"lineerr/{side} step={max(cfg['step'], st):.1f}",
               raw + ["RUN"],
               L.program(lab, "t", L.S2, "LINE(11,12)-(20,21)") + ["RUN"],
               boot=cfg["boot"], step=max(cfg["step"], st), cap_gap=2.5,
               reset=cfg["reset"])
print()

cfg = D.SIDES["zb"]
body = ["10 ON ERROR GOTO 900", "20 DEF FNA(X)=X+1",
        '60 CLS:PRINT"[";FNA(2);"]":END',
        '900 CLS:PRINT"[ERR";ERR;"AT";ERL;"]":END']
import probe_signal
report("deffn/zb", body + ["RUN"], probe_signal.mark_ends(body) + ["RUN"],
       boot=cfg["boot"], step=8.0, cap_gap=10.0, reset=cfg["reset"])
