#!/usr/bin/env python3
# Copyright (c) 2026 Joost Yervante Damad
# SPDX-License-Identifier: 0BSD

"""omsx_preflight -- refuse to measure a machine whose ROMs are missing or stale.

A probe names its openMSX machine as a STRING (`-machine C-BIOS_MSX1_EU_REPACK_DISK`)
and has no visibility into which files that name resolves to. So when the machine
XML points at a ROM that was deleted, or at one built before the sources it is
supposed to contain, the probe boots anyway and reports the absence of the ROM as
the absence of the FEATURE. Both directions have bitten this tree:

  * 2026-07-26 (traps T5): a control run repointed the shared machine at a worktree
    ROM, the worktree was deleted, and 32 of 42 gate cases came back `ERR 2` -- the
    exact signature of `INTERVAL` not existing, on a complete implementation
    ([[stale-machine-reads-as-unimplemented]]).
  * 2026-08-03 (D-DOTGAPS): a corpus script ran `rm -rf build && make basic-reloc`
    and then a probe, before any target had rebuilt the MERGED repack ROM the
    machine XML points at. Every row read `<none>` and the gate reported 55 red
    rows INCLUDING ITS OWN CONTROLS (docs/spec-basic-dotgaps.md s9.2).

Neither is detectable from inside the emulator: openMSX starts, the machine runs,
the screen scrapes cleanly. The only place the truth is available is BEFORE the
boot, on the host, where the XML and the files it names can both be read.

WHAT IS CHECKED (docs/spec-probe-preflight.md s3.2)
---------------------------------------------------
The machine XML is resolved by name and its <filename> elements are read.

  * ABSOLUTE paths OUTSIDE every openMSX share/user dir are this repo's (or
    another checkout's) build products -> checked.
  * bare / relative filenames, and paths INSIDE an openMSX share or user dir, are
    the user's own ROM set: openMSX resolves those through its systemroms search
    path and its sha1 database, so a missing FILE there is not necessarily a
    missing ROM -> NOT checked.

⚠️ THAT SECOND RULE IS WHAT KEEPS THE REFERENCE MACHINES OUT OF THE GUARD'S WAY,
AND IT IS STRUCTURAL RATHER THAN A NAME LIST. `Philips_VG_8020.xml` and
`National_CF-3300.xml` name their ROMs as bare filenames with sha1 siblings and
carry ZERO absolute paths, so a reference-only run checks nothing and can never be
refused. An `if machine in REFERENCE_MACHINES: return` exemption would have been a
filter of exactly the shape that blinded the lnblank echo guard
([[echo-guard-never-saw-say-rows]]) -- one edit away from exempting the subject.

Each checked file must:
  1. EXIST                                                   -> else MISSING
  2. be up to date, per `make -q <path>` in the repo root     -> else STALE
     (only for files under THIS repo's build/; this Makefile cannot speak for
     another checkout's build products)

🔴 THERE IS NO THIRD CHECK FOR THE mtime RACE, AND THAT IS A MEASUREMENT, NOT AN
OMISSION. [[make-mtime-race-skips-subrom]] records a rebuild `make` silently
skipped on an equal mtime, so this module shipped a check for it -- and the knife
aimed at that check found the check cannot exist:

  * GNU Make 3.81 (this host) compares mtimes at ONE-SECOND granularity. Measured
    on a two-file scratch Makefile: with the target 1 ns OLDER than its
    prerequisite, `make -q` still answers "up to date". So the hazard is not
    "equal mtime" as filed -- it is ANY pair inside the same whole second.
  * A same-second check FIRES ON A CORRECT, JUST-BUILT TREE. `sub/basic-resident-
    abi.inc` is GENERATED by the build (Makefile:261, tools/gen_resident_abi.py)
    68 ms before `build/sub.rom` consumes it, so every clean build produces the
    signature. The guard refused the clean tree before the knife ever cut.
  * Narrowing to "source strictly newer by a whole second" makes the check
    identical to `make -q` -- it stops being a second opinion.

So the sub-second race is REAL and NOT PREFLIGHTABLE: from mtimes alone, "raced"
and "built fast" are the same observation. It stays where the memory already puts
it -- hash the artifact in the knife runner, and `rm -rf build` before a build
whose input you just wrote.

WHY `make -q` AND NOT AN mtime SWEEP
------------------------------------
The obvious rule -- "no ROM older than the newest file under basic/ sub/ disk/
tape/" -- is WRONG, and would have refused every ordinary slice. `build/disk.rom`
depends on `disk/` only and `build/sub.rom` on `sub/` only, so editing
`basic/list.asm` and running `make repack-machine` (the correct, complete build
for a BASIC slice) leaves both older than the newest source under those four
directories. `make -q` asks the authority instead: the Makefile already holds the
per-artifact dependency map, and a second copy here is one more thing to drift --
which is the failure this module exists to prevent.

THE TRIGGER IS `-machine`, NOT THE BINARY NAME
----------------------------------------------
`guard_cmd` fires on the PRESENCE of `-machine` in the argv, not on
`basename(argv[0]) == "openmsx"`. A basename test is a filter, and a filter is
where a guard loses sight of its subject; nothing else in this tree takes
`-machine`, and preflighting a non-openMSX argv that happens to carry one costs a
stat.

ESCAPE HATCH
------------
`ZEROBAS_PREFLIGHT=off` skips the check and prints a banner to stderr on every
launch. A bug in here would otherwise wedge all 146 probes with no way out; the
banner is the price, because a bypass nobody can see is worse than no guard.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(_HERE))          # probes/lib -> probes -> repo
sys.path.insert(0, os.path.join(REPO, "tools"))
import openmsx_paths  # noqa: E402

BUILD = os.path.join(REPO, "build")

# argv operands that name a host file openMSX must be able to open. A missing
# cartridge or disk image is the same failure wearing different clothes: openMSX
# boots without it and the probe measures a machine it did not ask for.
FILE_OPTS = ("-cart", "-carta", "-cartb", "-diska", "-diskb")

_checked: dict[str, None] = {}          # machine -> already preflighted this process
_mkq: dict[str, int] = {}               # relpath -> `make -q` exit status
_hatch_warned = False


# --- host layout ------------------------------------------------------------

def _omsx_dirs() -> list[str]:
    """Every openMSX-owned directory: its share dirs and its user dirs. A
    <filename> under one of these is part of the user's own ROM set."""
    out = []
    for d in list(openmsx_paths.SHARE_CANDIDATES) + list(openmsx_paths.USER_CANDIDATES):
        if d and os.path.isdir(d):
            out.append(os.path.realpath(d))
    return out


def _under(path: str, roots: list[str]) -> bool:
    rp = os.path.realpath(path)
    return any(rp == r or rp.startswith(r + os.sep) for r in roots)


def machine_xml(name: str) -> str | None:
    """Resolve an openMSX machine name to its config file, searching the same
    places openMSX does: user dirs first (an installed machine SHADOWS a bundled
    one of the same name), then share dirs, then recursively under both."""
    seen: list[str] = []
    for u in openmsx_paths.USER_CANDIDATES:
        seen.append(os.path.join(u, "share", "machines"))
    for s in openmsx_paths.SHARE_CANDIDATES:
        seen.append(os.path.join(s, "machines"))
    for d in seen:
        cand = os.path.join(d, name + ".xml")
        if os.path.isfile(cand):
            return cand
    for d in seen:                       # machines may sit in a subdirectory
        if not os.path.isdir(d):
            continue
        for dirpath, _, files in os.walk(d):
            if name + ".xml" in files:
                return os.path.join(dirpath, name + ".xml")
    return None


_COMMENT = re.compile(r"<!--.*?-->", re.S)
_FILENAME = re.compile(r"<filename>\s*(.*?)\s*</filename>", re.S)


def xml_filenames(path: str) -> list[str]:
    """The <filename> texts of a machine config.

    Deliberately textual rather than `xml.etree`: the config
    `tools/install-repack-machine.py` writes has (had) a literal `--` inside an
    XML comment, which is illegal and makes ElementTree refuse the WHOLE file.
    openMSX's own parser tolerates it. A preflight that cannot read a config it
    is meant to vouch for is a guard that fails open, so comments are stripped
    and the elements read directly."""
    with open(path, "r", errors="replace") as f:
        text = f.read()
    return [m.strip() for m in _FILENAME.findall(_COMMENT.sub("", text))]


# --- the checks ------------------------------------------------------------

def _make_q(rel: str) -> int:
    """`make -q <rel>` in the repo root: 0 = up to date, 1 = out of date, 2 = make
    cannot judge it, -1 = make could not be run at all. Runs no recipe (measured
    at 11-17 ms). Memoised per process, so a batched matrix pays once."""
    if rel not in _mkq:
        try:
            p = subprocess.run(["make", "-q", rel], cwd=REPO,
                               stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            _mkq[rel] = p.returncode
        except BaseException:
            # 🔴 FAIL CLOSED, AND CATCH EVERYTHING TO DO IT. This was `except
            # OSError` and the E-matrix harness proved that too narrow: its test
            # double replaced `subprocess.Popen` globally, `subprocess.run` uses
            # that same global internally, and the harness exception escaped
            # `preflight` -- THROWING AWAY AN ALREADY-ACCUMULATED `MISSING` FAULT
            # and letting a machine with no ROM behind it through. A guard that
            # cannot judge must say so, never fall silent.
            _mkq[rel] = -1
    return _mkq[rel]


def check_file(path: str) -> tuple[str, str] | None:
    """Run the checks on one build product. Returns (REASON, detail) or None
    when the file is sound. See the module docstring on why there is no third,
    mtime-race check: it was built, knifed, and found to be unbuildable."""
    if not os.path.isfile(path):
        return ("MISSING", "the machine points at a file that does not exist")
    if not _under(path, [os.path.realpath(BUILD)]):
        # Another checkout's build/ (a worktree control run left behind). It
        # exists, which is all this Makefile can honestly say about it.
        return None
    rel = os.path.relpath(os.path.realpath(path), REPO)
    rc = _make_q(rel)
    if rc == 1:
        return ("STALE", f"`make -q {rel}` says it is out of date w.r.t. its sources")
    if rc == 2:
        return ("NO-RULE", f"`make -q {rel}` cannot judge it (no rule?)")
    if rc == -1:
        return ("NO-MAKE", "`make` is not available, so freshness cannot be judged")
    return None


# --- the guard ---------------------------------------------------------------

def _fail(machine: str, xml: str | None, faults: list[tuple[str, str, str]]) -> None:
    w = 74
    out = [
        "",
        "=" * w,
        "APPARATUS FAILURE -- openMSX preflight: NOTHING WAS MEASURED",
        "=" * w,
        f"  machine : {machine}",
        f"  config  : {xml if xml else '<not found>'}",
        "",
    ]
    for reason, what, detail in faults:
        out.append(f"  {reason:<11} {what}")
        out.append(f"  {'':<11} {detail}")
    out += [
        "",
        "  FIX: make repack-machine        (rebuilds the ROMs AND reinstalls the",
        "                                   machine config that points at them)",
        "",
        "  A probe booted against this machine would report the absence of the",
        "  ROM as the absence of the FEATURE -- a whole class of cases failing",
        "  identically, which reads exactly like a catastrophic regression.",
        "  Refused instead of measured.  (docs/spec-probe-preflight.md)",
        "=" * w,
        "",
    ]
    print("\n".join(out), file=sys.stderr)
    raise SystemExit(2)


def preflight(machine: str, *, files: list[str] = ()) -> None:
    """Refuse (SystemExit 2) unless `machine` resolves to a config whose repo-built
    ROMs all exist and are up to date, and every path in `files` exists.

    Idempotent and memoised per machine per process: a batched matrix pays for
    this once, and a boot-per-case run pays for it once too."""
    global _hatch_warned
    if os.environ.get("ZEROBAS_PREFLIGHT", "").lower() in ("off", "0", "no"):
        if not _hatch_warned:
            print("⚠️  ZEROBAS_PREFLIGHT=off -- openMSX preflight DISABLED; a "
                  "missing or stale ROM will be measured as a code result.",
                  file=sys.stderr)
            _hatch_warned = True
        return

    faults: list[tuple[str, str, str]] = []
    for p in files:
        if p and not os.path.exists(p):
            faults.append(("MISSING", os.path.relpath(p, REPO)
                           if p.startswith(REPO) else p,
                           "argv names a cartridge/disk image that does not exist"))
    if faults:                          # report these even for a cached machine
        _fail(machine, machine_xml(machine), faults)

    if machine in _checked:
        return

    xml = machine_xml(machine)
    if xml is None:
        _fail(machine, None,
              [("NO-MACHINE", machine,
                "no such machine config in any openMSX user or share dir")])
    omsx_dirs = _omsx_dirs()
    for fn in xml_filenames(xml):
        if not os.path.isabs(fn):
            continue                    # openMSX resolves it via systemroms/sha1
        if _under(fn, omsx_dirs):
            continue                    # the user's own ROM set, not ours to judge
        verdict = check_file(fn)
        if verdict:
            reason, detail = verdict
            what = os.path.relpath(fn, REPO) if fn.startswith(REPO + os.sep) else fn
            faults.append((reason, what, detail))
    if faults:
        _fail(machine, xml, faults)
    _checked[machine] = None


def guarded(cmd):
    """`subprocess.Popen(omsx_preflight.guarded(cmd), ...)` -- preflight the argv
    and hand it straight back. THE call every launch site in this tree makes.

    It WRAPS the argument rather than sitting on the line above it so that the
    guard cannot be aimed at anything other than the list actually being spawned.
    A separate `guard_cmd(cmd)` statement is one careless edit away from guarding
    a variable the spawn no longer uses -- a guard filtered away from its own
    subject, which is the failure mode this whole module is built against
    ([[echo-guard-never-saw-say-rows]]). Wrapping makes that unexpressible, and it
    is what tools/check_probe_preflight.py looks for."""
    guard_cmd(cmd)
    return cmd


def guard_cmd(cmd) -> None:
    """Preflight an about-to-be-spawned argv. A no-op unless it carries `-machine`.

    THIS is what every launch site calls, so it must not care what the argv looks
    like otherwise: `cmd` may be a list or a shell string, and argv[0] may be any
    of the four ways this tree spells the openMSX binary."""
    if isinstance(cmd, str):
        m = re.search(r"-machine\s+(\S+)", cmd)
        if not m:
            return
        preflight(m.group(1).strip("'\""))
        return
    argv = [str(a) for a in cmd]
    if "-machine" not in argv:
        return
    i = argv.index("-machine")
    if i + 1 >= len(argv):
        return                          # malformed; openMSX will complain itself
    files = [argv[j + 1] for j, a in enumerate(argv)
             if a in FILE_OPTS and j + 1 < len(argv)]
    preflight(argv[i + 1], files=files)


# --- CLI --------------------------------------------------------------------

def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("machine", nargs="*", help="machine name(s) to preflight")
    ap.add_argument("--verbose", "-v", action="store_true",
                    help="print every file and its verdict (the denominator)")
    args = ap.parse_args()
    if not args.machine:
        ap.error("name at least one machine")
    for m in args.machine:
        xml = machine_xml(m)
        if args.verbose:
            print(f"=== {m}")
            print(f"    config: {xml}")
            if xml:
                omsx_dirs = _omsx_dirs()
                n = 0
                for fn in xml_filenames(xml):
                    if not os.path.isabs(fn):
                        print(f"    skip   {fn}  (relative -> openMSX systemroms)")
                        continue
                    if _under(fn, omsx_dirs):
                        print(f"    skip   {fn}  (openMSX-owned dir)")
                        continue
                    n += 1
                    v = check_file(fn)
                    tag = "OK" if v is None else v[0]
                    print(f"    {tag:<11}{fn}"
                          + ("" if v is None else f"  -- {v[1]}"))
                print(f"    checked {n} file(s)")
        preflight(m)
        print(f"preflight OK: {m}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
