#!/usr/bin/env python3
# Copyright (c) 2026 Joost Yervante Damad
# SPDX-License-Identifier: 0BSD

"""Drive openMSX headlessly and capture machine state to a file.

This is the reusable core of the openMSX comparison harness: boot a machine
(optionally with a cartridge), run until a deterministic event, then dump CPU
registers and/or memory blocks. It is the foundation for the (parked) VG8020 vs
C-BIOS MSX1 behavioural diff — see docs/openmsx-harness.md.

Determinism notes learned the hard way:

* openMSX is deterministic given the same machine + inputs: two identical runs
  produce byte-identical dumps. We rely on that.
* Do NOT sync on a fixed *emulated time*: real-BIOS machines boot slower than
  C-BIOS, so a cartridge INIT that has run on C-BIOS by t=3s may not have run on
  a VG-8020 yet. Sync on an *event* instead -- a breakpoint at a known address
  (e.g. a "done" landmark your test cartridge jumps to). `--bp` does this and is
  the recommended mode. `--time` is offered only as a fallback.
* Headless = `set renderer none` + `set throttle off`. Tcl `puts` goes to
  openMSX's own console, never the host stdout, so all capture goes to a file.

Example
-------
    python3 probes/lib/omsx_run.py --machine C-BIOS_MSX1 --cart sentinel.rom \\
        --bp 0x7FF0 --reg PC --mem memory:0xE000:4 --out cap.txt
"""
from __future__ import annotations

import argparse
import os
import shlex
import signal
import subprocess
import sys
import tempfile
import time
# --- zerobas: the openMSX preflight guard (probes/lib) ---
import os as _zbo, sys as _zbs  # noqa: E402
_zbs.path.insert(0, _zbo.path.dirname(_zbo.path.abspath(__file__)))
import omsx_preflight  # noqa: E402

# openMSX 21.0 (Homebrew-bin symlink -> /Applications/openMSX.app). Override with
# $OPENMSX or --omsx; e.g. point at a self-built source clone for C-BIOS work.
DEFAULT_OMSX = "/opt/homebrew/bin/openmsx"


def find_omsx(explicit: str | None) -> str:
    for cand in (explicit, os.environ.get("OPENMSX"), DEFAULT_OMSX, "openmsx"):
        if not cand:
            continue
        if os.path.sep in cand:
            if os.path.isfile(cand) and os.access(cand, os.X_OK):
                return cand
        else:  # bare name -> trust PATH
            return cand
    raise SystemExit("openMSX binary not found; pass --omsx or set $OPENMSX")


def parse_mem(spec: str) -> tuple[str, int, int]:
    """`NAME:ADDR:LEN` -> (debuggable, addr, len). NAME may contain spaces."""
    name, addr, length = spec.rsplit(":", 2)
    return name, int(addr, 0), int(length, 0)


def _tcl_dquote(s: str) -> str:
    """Render a string as a Tcl double-quoted literal.

    Control characters become escapes (CR -> \\r) so they survive being written
    into a script file, and Tcl-special characters are backslash-escaped to
    prevent substitution. Used for the `type` argument: a literal CR byte placed
    in `{...}` braces gets mangled and the Enter keystroke is lost.
    """
    out = []
    for ch in s:
        if ch == "\r":
            out.append("\\r")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch in '\\"$[]':
            out.append("\\" + ch)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def build_tcl(out_path: str, regs: list[str], mems: list[str],
              bp: int | None, secs: float | None,
              type_events: list[tuple[float, str]] | None = None,
              record: str | None = None) -> str:
    lines = [
        "# generated by omsx_run.py -- headless state capture",
        "set throttle off",
        "proc __hex {dbg addr len} {",
        "  binary scan [debug read_block $dbg $addr $len] H* h; return $h",
        "}",
    ]
    if record is not None:
        # Start a fresh tape in record mode before the cart INIT can write to
        # CAS-out, so the whole write session is captured (see cas_decode.py).
        lines.append(f"cassetteplayer new {{{record}}}")
    lines += [
        "proc __capture {} {",
        f"  set f [open {{{out_path}}} w]",
        '  puts $f "machine=[machine_info config_name]"',
    ]
    for r in regs:
        lines.append(f'  puts $f "reg.{r}=[format 0x%04X [reg {r}]]"')
    for m in mems:
        name, addr, length = parse_mem(m)
        key = f"{name}:0x{addr:04X}:{length}"
        lines.append(f'  puts $f "mem.{key}=[__hex {{{name}}} {addr} {length}]"')
    if record is not None:
        # Eject flushes and closes the recorded tape file to disk.
        lines.append('  puts $f "tape.length=[cassetteplayer getlength]"')
        lines.append("  catch {cassetteplayer eject}")
    lines += ["  close $f", "  exit", "}"]
    # Keyboard injections, each scheduled at its own emulated time. Multiple
    # events (e.g. a command then a separate, later Enter) inject in distinct
    # time windows, which is more reliable than one burst under `throttle off`.
    # Emit each as a Tcl double-quoted literal so control characters survive as
    # escapes (a literal CR byte in braces gets mangled and the Enter is lost).
    # `type --` ends option parsing so a payload that starts with '-' (e.g. a
    # negative-number INPUT response "-7") is typed verbatim instead of being
    # swallowed as a command switch.
    for delay, text in (type_events or []):
        lines.append(f"after time {delay} {{ type -- {_tcl_dquote(text)} }}")
    if bp is not None:
        lines.append(f"debug set_bp {bp} {{}} {{ __capture }}")
    else:
        lines.append(f"after time {secs} {{ __capture }}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--machine", required=True, help="openMSX machine id, e.g. C-BIOS_MSX1")
    ap.add_argument("--cart", help="cartridge ROM to insert")
    ap.add_argument("--cassette", help="cassette image (.cas/.wav) to insert")
    ap.add_argument("--record", metavar="WAV",
                    help="record CAS-out to a new tape file (decode with cas_decode.py)")
    ap.add_argument("--type", dest="type_str", action="append", default=[],
                    metavar="STRING",
                    help="keyboard-inject STRING after boot (repeatable; e.g. "
                         "'BLOAD\"CAS:\",R\\r'). Pair each with a --type-delay.")
    ap.add_argument("--type-delay", type=float, action="append", default=[],
                    metavar="SECS",
                    help="emulated seconds before the matching --type injection "
                         "(repeatable, paired by position; default 3)")
    ap.add_argument("--reg", action="append", default=[], metavar="NAME",
                    help="CPU register to dump (repeatable): PC, A, SP, ...")
    ap.add_argument("--mem", action="append", default=[], metavar="DBG:ADDR:LEN",
                    help="memory block to dump (repeatable), e.g. memory:0xE000:4")
    grp = ap.add_mutually_exclusive_group()
    grp.add_argument("--bp", type=lambda s: int(s, 0), metavar="ADDR",
                     help="run until a breakpoint at ADDR fires (recommended)")
    grp.add_argument("--time", type=float, metavar="SECS",
                     help="fallback: run until SECS of emulated time elapse")
    ap.add_argument("--out", required=True, help="capture output file")
    ap.add_argument("--omsx", help="path to openmsx binary")
    ap.add_argument("--timeout", type=float, default=60.0,
                    help="host-side watchdog seconds (default 60)")
    ap.add_argument("--keep-tcl", action="store_true", help="don't delete the generated Tcl")
    args = ap.parse_args()

    if args.bp is None and args.time is None:
        args.time = 6.0  # generous: safely past both C-BIOS and real-BIOS boot

    # Pair each --type with its --type-delay by position (default 3.0s).
    type_events = [(args.type_delay[i] if i < len(args.type_delay) else 3.0, s)
                   for i, s in enumerate(args.type_str)]

    omsx = find_omsx(args.omsx)
    if os.path.exists(args.out):
        os.unlink(args.out)

    tcl = build_tcl(os.path.abspath(args.out), args.reg, args.mem, args.bp, args.time,
                     type_events=type_events,
                     record=os.path.abspath(args.record) if args.record else None)
    fd, tcl_path = tempfile.mkstemp(suffix=".tcl", prefix="omsx_")
    os.write(fd, tcl.encode())
    os.close(fd)

    cmd = [omsx, "-machine", args.machine]
    if args.cart:
        cmd += ["-cart", args.cart]
    if args.cassette:
        cmd += ["-cassetteplayer", args.cassette]
    cmd += ["-command", "set renderer none; set sound_driver null", "-script", tcl_path]

    try:
        proc = subprocess.Popen(omsx_preflight.guarded(cmd), stdout=subprocess.DEVNULL,
                                stderr=subprocess.DEVNULL, start_new_session=True)
        deadline = time.time() + args.timeout
        while proc.poll() is None and time.time() < deadline:
            time.sleep(0.1)
        if proc.poll() is None:
            os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            print(f"omsx_run: TIMEOUT after {args.timeout}s "
                  f"({shlex.join(cmd)})", file=sys.stderr)
            return 2
    finally:
        if not args.keep_tcl:
            os.unlink(tcl_path)

    if not os.path.exists(args.out):
        print("omsx_run: openMSX exited without writing a capture "
              "(breakpoint never hit? bad machine/cart?)", file=sys.stderr)
        return 1
    with open(args.out) as f:
        sys.stdout.write(f.read())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
